version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: fcm-django
    versions:
    - 0.3.7
    - 0.3.8
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: django-bootstrap4
    versions:
    - 2.3.1
  commit-message:
    prefix: Crowdbotics
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: react-native-image-picker
    versions:
    - 3.1.4
    - 3.2.0
    - 3.2.1
    - 3.3.2
    - 3.3.3
    - 3.3.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-native-keyboard-aware-scroll-view
    versions:
    - 0.9.3
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  commit-message:
    prefix: Crowdbotics
